<div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only"><?php echo $this->__('Toggle navigation'); ?></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
    </button>
</div>
<div class="collapse navbar-collapse">
    <ul class="nav navbar-nav">
        <li class="active"><a href="#"><?php echo $this->__('Friday Lock'); ?></a></li>
        <li><a href="#keyless"><?php echo $this->__('Keyless'); ?></a></li>
        <li><a href="#sharing"><?php echo $this->__('Sharing'); ?></a></li>
        <li><a href="#design"><?php echo $this->__('Design'); ?></a></li>
        <li><a href="#construction"><?php echo $this->__('Construction'); ?></a></li>
        <li><a class="buy_now" href="<?= $this->getUrl('bundle.html') ?>"><?php echo $this->__('Buy now'); ?></a></li>
    </ul>
</div>