<div class="product-shop-footer">
  <div class="what-installation-kit">
    <span class="wik-toggle"><?= $this->__('What installation kit do I need?') ?></span>
    <div class="wik-popup">
      <div class="h4"><?= $this->__('What installation kit do I need?') ?></div>
      <div class="wik-text">
        <p>If you're in the US etc etc...</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
            Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
            Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.
        </p>
      </div>
    </div>
  </div>
  <div class="free-shipping">
    <?= $this->__('Free shipping on all orders') ?>
  </div>
</div>