<section class="control-block col-lg-12 col-md-12 col-sm-12">
    <div class="control col-lg-4 col-md-4 col-sm-4">
        <h3 class="first-title">
            <?php echo $this->__('Control'); ?>
        </h3>
        <br/>
        <h2 class="second-title">
            <?php echo $this->__('Your home, at your fingertips'); ?>
        </h2>
        <br/>
        <p class="selection-text">
            <?php echo $this->__('Recieve notifications of all entries and exists so you always know who\'s at home.'); ?>
        </p>
    </div>
    <div class="time-block col-lg-8 col-md-8 col-sm-8">
        <div class="col-lg-8 col-md-8 col-sm-8">
            <h2>
                12:30 am
            </h2>
            <p class="text">
                Handyman leave the house.
            </p>
        </div>
    </div>
</section>