<section class="friday-app-block col-lg-12 col-md-12 col-sm-12">
    <div class="friday-app col-lg-4 col-md-4 col-sm-4">
        <h3 class="first-title">
            <?php echo $this->__('Friday App'); ?>
        </h3>
        <h2 class="selection-text">
            <?php echo $this->__('The app lets you control all your locks and grant or deny access with th touch of a button.'); ?>
        </h2>
        <a href="#buy" class="buy_now view_app">
            <?php echo $this->__('View app'); ?>
        </a>
    </div>
    <div class="sharing-block col-lg-8 col-md-8 col-sm-8">
        <h3 class="first-title">
            <?php echo $this->__('Sharing'); ?>
        </h3>
        <br/>
        <h2 class="second-title">
            <?php echo $this->__('Share access to friends and family'); ?>
        </h2>
        <br/>
        <p class="selection-text">
            <?php echo $this->__('Issue temporary or perma&shy;nent keys to friends and family in a matter of se&shy;conds, and revoke them again whenever you need to. No more running to the door or leaving spare keys under the doormat.'); ?>
        </p>
    </div>
</section>