<section class="how-it-works col-lg-12 col-md-12 col-sm-12">
    <div class="tell-siri col-lg-4 col-md-4 col-sm-4">
        <h2 class="second-title">
            <?php echo $this->__('Tell siri <br/> to open your door'); ?>
        </h2>
        <p class="selection-text">
            <?php echo $this->__('Friday connects to your phone via Bluetooth or WI-FI, It is also HomeKit certified, meaning Siri can open your door.'); ?>
        </p>
        <p class="icons">
            <span class="house"></span>
            <span class="wifi"></span>
            <span class="bluetooth"></span>
        </p>
    </div>
    <div class="fits col-lg-5 col-md-5 col-sm-5">
        <h2 class="second-title">
            <?php echo $this->__('Fits on <br/> most locks'); ?>
        </h2>
    </div>
    <div class="no-handyman col-lg-3 col-md-3 col-sm-3">
        <h2 class="second-title">
            <?php echo $this->__('You don\'t need <br/> a handyman'); ?>
        </h2>
    </div>
    <div class="no-unwanted col-lg-3 col-md-3 col-sm-3">
        <h2 class="second-title">
            <?php echo $this->__('No unwanted <br/> attention'); ?>
        </h2>
    </div>
    <div class="safety col-lg-5 col-md-5 col-sm-5">
        <h2 class="second-title">
            <?php echo $this->__('Safety is <br/> our top priority'); ?>
        </h2>
    </div>
</section>