<section class="keyless-block">
    <h3 class="first-title">
        <?php echo $this->__('Keyless'); ?>
    </h3>
    <h2 class="second-title">
        <?php echo $this->__('turn your phone into your key'); ?>
    </h2>
    <p class="selection-text">
        <?php echo $this->__('With Friday Smart Lock you\'ll neven have to worry about losing your keys or locking yourself out of your home again. It recognises you via your phone as you approach, unlocking the door automatically.'); ?>
    </p>
</section>