<section class="slider-block col-lg-12 col-md-12 col-sm-12">
    <div class="bxslider col-lg-12 col-md-12 col-sm-12">
        <div class="first-slide col-lg-12 col-md-12 col-sm-12">
            <h3 class="first-title">
                <?php echo $this->__('Construction'); ?>
            </h3>
            <h2 class="second-title">
                <?php echo $this->__('Take a closer look'); ?>
            </h2>
            <p class="selection-text">
                <?php echo $this->__('Friday features interchangable shells all made out of natural materials, to fit perfectly in any home.'); ?>
            </p>
        </div>
        <div class="second-slide col-lg-12 col-md-12 col-sm-12">
            <h3 class="first-title">
                <?php echo $this->__('Construction'); ?>
            </h3>
            <h2 class="second-title">
                <?php echo $this->__('Take a closer look'); ?>
            </h2>
            <p class="selection-text">
                <?php echo $this->__('Friday features interchangable shells all made out of natural ma&shy;terials, to fit perfectly in any home.'); ?>
            </p>
        </div>
    </div>
</section>

<script>
    (function($){
        $(document).ready(function(){            
            $('.bxslider').bxSlider({
				auto: true,
				controls: false,
				pager: false
			});
        })
    })(jQuery)
</script>